In [37]:
import numpy as np

In [38]:
import time 

# Create a list of 1 million  numbers

In [39]:
pyhton_list = list(range(1000000))

In [40]:
numpy_array = np.array(range(1000000))

# Method 1 : Python loop

In [41]:
start = time.time()
result_loop = [x * 2 for x in  pyhton_list]
print("Pyhton loop time : ", time.time() - start, " Seconds")

Pyhton loop time :  0.02800440788269043  Seconds


# Mehtod 2 : Numpy vectorization

In [42]:
start = time.time()
result_loop = numpy_array * 2
print("Numpy time : " ,time.time() - start, " Seconds")

Numpy time :  0.00790548324584961  Seconds


In [43]:
# Python list - each element is a Python object
# stored randomly in memory
python_list = [1, 2, 3, 4, 5]

# NumPy array - all elements same type
# stored in continuous memory block
numpy_array = np.array([1, 2, 3, 4, 5])

print("Python list type:", type(python_list[0]))
print("NumPy array dtype:", numpy_array.dtype)
print("NumPy array shape:", numpy_array.shape)
print("NumPy array size:", numpy_array.size)
print("NumPy memory (bytes):", numpy_array.nbytes)

Python list type: <class 'int'>
NumPy array dtype: int64
NumPy array shape: (5,)
NumPy array size: 5
NumPy memory (bytes): 40


Python wastes memory storing type information for every single element. NumPy stores type once for the entire array.
That's why NumPy is faster — less memory = faster access = faster computation.

# Array Operations

In [44]:
a = np.array([1,2,3,4,5])

In [45]:
b = np.array([10,20,30,40,50])

In [46]:
#Predict output before running each Line

print(a+b)
print(a*b)
print(a**2)
print(a+10)
print(a*10)
print(a>3)
print(a[a>3])


[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
[11 12 13 14 15]
[10 20 30 40 50]
[False False False  True  True]
[4 5]


# Broadcasting

In [47]:
a = np.array([1,2,3,4,5])

In [48]:
print(a+100)

[101 102 103 104 105]


In [49]:
print(a*0)

[0 0 0 0 0]


In [50]:
print(a*0)

[0 0 0 0 0]


In [51]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [52]:
print(matrix + 10)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [53]:
print(matrix*  2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [54]:
print(matrix[1])

[4 5 6]


In [55]:
print(matrix[1][2])

6


In [56]:
print(matrix[:,1])

[2 5 8]


In [57]:
print(matrix[0, :])

[1 2 3]


# ML connection

In [58]:
# This is what happen in Logistic Regression

# Fake wieght
weight = np.array([0.5,-2.1,0.3])

In [59]:

passenger = np.array([2,0,25]) #Pclass, Sex,  Age

In [60]:
z = np.dot(weight,passenger)
print("Weighted sum z:", z)

Weighted sum z: 8.5


In [61]:
# Sigmoid function = converts  to probability 

def signoid(x):
    return 1 / (1+ np.exp(-x))

In [62]:
probability = signoid(z)

In [63]:

print("Survival Probability : ", round(probability * 100, 1), "%")

Survival Probability :  100.0 %


# By model

In [68]:
weights = np.array([-0.5528, 2.1375, -0.0313, 
                    -0.6255, -0.1250, 0.0160, 0.7433])

In [73]:
# Sonu's features
sonu = np.array([2,0,21,2,1,20,0])

In [82]:
# Dot product 
z = np.dot(weights,sonu) + 0.5788779288662111
probability = signoid(z)
print("Sonu Survival probability: ", round(probability * 100 , 1), "%")

Sonu Survival probability:  9.6 %


In [83]:
# Her features
her = np.array([1,1,20,0,0,100,1])

In [84]:

z = np.dot(weights,her) + 0.5788779288662111

In [85]:
probability = signoid(z)

In [86]:
print("Shree Survival Probability:", round(probability * 100,1), "%")

Shree Survival Probability: 98.0 %


In [87]:
# Logistic Regression is just:
# 1. Weighted sum of features + intercept
# 2. Sigmoid squashes result to 0-1
# 3. Threshold at 0.5 for binary prediction
#
# model.coef_     = learned weights
# model.intercept_ = learned bias
# np.dot()        = weighted sum
# sigmoid()       = probability conversion
#
# Everything else is just finding the right weights
# That process = gradient descent (Week 3)