In [1]:
import numpy as np 

# XOR Dataset 

In [3]:
X = np.array([[0,0],
             [0,1],
              [1,0],
              [1,1]
             ])

In [4]:
y = np.array([
    [0],[1],[1],[0]
])

# Forward Pass 

In [5]:
def sigmoid(z):
    s = 1/(1+ np.exp(-z))
    return s

# INitializing

In [44]:
np.random.seed(42)

W1 = np.random.randn(2,4)
b1 = np.zeros((1,4))      
W2 = np.random.randn(4,1)
b2 = np.zeros((1,1))       

In [45]:
# Forward pass function 

In [46]:
def forward(X,W1,b1,W2,b2):
    # LAyer 1 : Input to hiden 
    z1 = X @ W1 + b1
    a1 = sigmoid(z1)

    # LAyer 2 : hiden to Output 
    z2 = a1 @ W2 + b2
    a2 = sigmoid(z2)

    return a1, a2

In [47]:
a1, a2 = forward(X, W1, b1, W2, b2)
print("Predictions before training:")
print(a2)

Predictions before training:
[[0.39459663]
 [0.33849512]
 [0.32609598]
 [0.29208992]]


In [48]:
def compute_loss(y_true, y_pred):
    m = y_true.shape[0]  
    loss = -(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
    return loss.mean()

In [49]:
loss = compute_loss(y, a2)
print(f"Loss before training: {loss}")

Loss before training: 0.7627769104532394


In [50]:
def backward(X, y, a1, a2, W2):
    m = X.shape[0]
    
    # Output layer gradients
    dz2 = a2 - y
    dW2 = a1.T @ dz2 / m
    db2 = dz2.sum(axis=0, keepdims=True) / m
    
    # Hidden layer gradients
    dz1 = (dz2 @ W2.T) * a1 * (1 - a1)
    dW1 = X.T @ dz1 / m
    db1 = dz1.sum(axis=0, keepdims=True) / m
    
    return dW1, db1, dW2, db2

In [51]:
dW1, db1, dW2, db2 = backward(X, y, a1, a2, W2)
print("Gradient shapes:")
print(f"dW1: {dW1.shape}, db1: {db1.shape}")
print(f"dW2: {dW2.shape}, db2: {db2.shape}")

Gradient shapes:
dW1: (2, 4), db1: (1, 4)
dW2: (4, 1), db2: (1, 1)


In [52]:
learning_rate = 1.0
epochs = 10000

In [53]:
losses = []

In [54]:
for epoch in range(epochs):
    # Forward pass
    a1, a2 = forward(X, W1, b1, W2, b2)
    
    # Compute loss
    loss = compute_loss(y, a2)
    losses.append(loss)
    
    # Backward pass
    dW1, db1, dW2, db2 = backward(X, y, a1, a2, W2)
    
    # Update weights
    W1 -= learning_rate * dW1
    b1 -= learning_rate * db1
    W2 -= learning_rate * dW2
    b2 -= learning_rate * db2
    
    # Print progress
    if epoch % 1000 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

print("\nFinal predictions:")
a1, a2 = forward(X, W1, b1, W2, b2)
print(a2)
print("\nTarget:")
print(y)


Epoch 0, Loss: 0.7628
Epoch 1000, Loss: 0.0147
Epoch 2000, Loss: 0.0040
Epoch 3000, Loss: 0.0022
Epoch 4000, Loss: 0.0015
Epoch 5000, Loss: 0.0011
Epoch 6000, Loss: 0.0009
Epoch 7000, Loss: 0.0007
Epoch 8000, Loss: 0.0006
Epoch 9000, Loss: 0.0005

Final predictions:
[[2.29610155e-04]
 [9.99607397e-01]
 [9.99421026e-01]
 [6.96705159e-04]]

Target:
[[0]
 [1]
 [1]
 [0]]
